### ISSUE TITLE
Suggestion: Make the unblurring automatic

### ISSUE THREAD

**Issue by Invisible40** [kush789/Unblur-Scribd#3]
The extension seems to work so far, but I have a suggestion. I think the extension should unblur the Scribd document automatically, instead of having to press a button.

Another thing I noticed was that when you use the "Search document" feature, it goes back to being blurred. Pressing the icon fixes it again, but this should also be fixed in my opinion.

**Comment by kush789** [comment]
Thanks for the input, didn't know the "Search document" feature breaks it. I'll try to fix it as soon as I get some free time

**Comment by Invisible40** [comment]
Nice, and thank you!

**Comment by kush789** [comment]
So I added a timeout, the extension keeps un-blurring pages as they get loaded. However it needs to be clicked at least once (to begin un blurring).

I couldn't replicate the bug that you mentioned (Search feature breaking the code), however this timeout should take care of that as well :D

**Comment by Invisible40** [comment]
Sweet! I'll let you know if I get the issue again. :)
